
# APPLICATION


spring.application.name=carecircle-eureka-server
server.port=${PORT:8761}


# EUREKA SERVER


eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=localhost



# LOGGING


logging.level.com.netflix.eureka=INFO
logging.level.org.springframework.cloud.netflix.eureka=INFO