spring.application.name=carecircle-auth-service

server.port=8081


# DATABASE
#spring.datasource.url=jdbc:mysql://localhost:3306/carecircle_auth_db
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/carecircle_auth_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${MYSQL_ROOT_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT


jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# EUREKA


eureka.client.service-url.defaultZone=http://carecircle-eureka:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

 

eureka.instance.hostname=carecircle-auth
eureka.instance.prefer-ip-address=false