
# APPLICATION


spring.application.name=health-record-service
server.port=8085


# MONGODB


spring.data.mongodb.uri=mongodb://localhost:27017/healthrecords



# MULTIPART / FILE UPLOAD


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=2KB


# MINIO


minio.url=http://127.0.0.1:9001
minio.access-key=minioadmin
minio.secret-key=${MINIO_ACCESS_KEY}
minio.bucket=medical-files



# JWT

jwt.secret=${JWT_SECRET}



# EUREKA


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1


# LOGGING


logging.level.io.minio=DEBUG
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.carecircle.healthrecords=DEBUG



# JSON


spring.jackson.default-property-inclusion=non_null