
# APPLICATION


spring.application.name=health-metrics-service
server.port=8088



# DATABASE


#spring.datasource.url=jdbc:mysql://localhost:3306/carecircle_health_metrics
spring.datasource.url=jdbc:mysql://localhost:3306/carecircle_health_metrics?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${MYSQL_ROOT_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect




# LOGGING


logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE



# EUREKA


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# IMPORTANT FOR API GATEWAY
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1


# JWT


jwt.secret=${JWT_SECRET}



# FEIGN CLIENT LOGGING


logging.level.org.springframework.cloud.openfeign=DEBUG